//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name="UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV", Namespace="http://www.UFIDA.org", ConfigurationName="UFIDAU9ISVItemIBatchQueryItemByDTOSRV")]
public interface UFIDAU9ISVItemIBatchQueryItemByDTOSRV
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/Do", ReplyAction="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail), Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoServiceException" +
        "DetailFault", Name="ServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.ExceptionBase), Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoExceptionBaseFau" +
        "lt", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceException), Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoServiceException" +
        "Fault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.FaultContractAttribute(typeof(UFSoft.UBF.Service.ServiceLostException), Action="http://www.UFIDA.org/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV/DoServiceLostExcep" +
        "tionFault", Name="ServiceLostException", Namespace="http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.PlatformContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.PL.Engine.ObjectState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangDataDict))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Util.Data.MultiLangData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DataRowState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemQueryItemDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemQueryItemDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFSoftUBFBusinessDataTransObjectBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CBOPubControllerCommonArchiveDataDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9CBOPubControllerContextDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9BaseFlexFieldDescFlexFieldDescFlexSegmentsData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9BasePropertyTypesEffectiveData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemEntranceInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemInspectionInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemInvInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterVersionDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterVersionDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemTradeMarkDTOData[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemTradeMarkDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMFGInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemMRPInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemPurchaseInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(www.ufida.org.EntityData.UFIDAU9ISVItemItemSaleInfoDTOData))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UFSoft.UBF.Exceptions1.MessageBase[]))]
    www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterDTOData[] Do(out UFSoft.UBF.Exceptions1.MessageBase[] outMessages, object context, www.ufida.org.EntityData.UFIDAU9ISVItemQueryItemDTOData[] queryItemDTOs, www.ufida.org.EntityData.UFIDAU9CBOPubControllerContextDTOData contextDTO);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface UFIDAU9ISVItemIBatchQueryItemByDTOSRVChannel : UFIDAU9ISVItemIBatchQueryItemByDTOSRV, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient : System.ServiceModel.ClientBase<UFIDAU9ISVItemIBatchQueryItemByDTOSRV>, UFIDAU9ISVItemIBatchQueryItemByDTOSRV
{
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient()
    {
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public www.ufida.org.EntityData.UFIDAU9ISVItemItemMasterDTOData[] Do(out UFSoft.UBF.Exceptions1.MessageBase[] outMessages, object context, www.ufida.org.EntityData.UFIDAU9ISVItemQueryItemDTOData[] queryItemDTOs, www.ufida.org.EntityData.UFIDAU9CBOPubControllerContextDTOData contextDTO)
    {
        return base.Channel.Do(out outMessages, context, queryItemDTOs, contextDTO);
    }
}
